import { defineConfig } from "vitest/config";
import preact from "@preact/preset-vite";
import tailwindcss from "@tailwindcss/vite";
import { writeFileSync } from "node:fs";
import { fileURLToPath, URL } from "node:url";

const staticMarker = fileURLToPath(new URL("../internal/studio/static/.gitkeep", import.meta.url));

export default defineConfig({
  root: fileURLToPath(new URL(".", import.meta.url)),
  base: "./",
  plugins: [preact(), tailwindcss(), {
    name: "keep-static-embed-directory",
    closeBundle() {
      writeFileSync(staticMarker, "Generated by `npm run build:studio`. Kept so Go's embed directive has a valid directory in source checkouts.\n");
    },
  }],
  build: {
    outDir: "../internal/studio/static",
    emptyOutDir: true,
  },
  test: {
    environment: "jsdom",
    setupFiles: ["./src/test-setup.ts"],
  },
});
